[package]
org = "ballerinax"
name = "health.fhir.r4.davincihrex100"
version = "1.0.0"
distribution = "2201.8.6"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "DaVinci", "HREX"]
export = ["health.fhir.r4.davincihrex100"]
