[package]
authors = ["Ballerina"]
distribution = "2201.10.2"
export = ["health.fhir.r4.davinciplannet120"]
keywords = ["Healthcare", "FHIR", "R4", "health_fhir_r4_davinciplannet120"]
name = "health.fhir.r4.davinciplannet120"
org = "ballerinax"
version = "1.0.0"
