[package]
org = "ballerinax"
name = "health.fhir.r4.validator"
version = "4.2.1"
distribution = "2201.8.6"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "Validator"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"
export = ["health.fhir.r4.validator"]

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.parser"
version = "5.0.2"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.international401"
version = "2.0.2"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.uscore501"
version = "1.3.3"
repository = "local"

