[package]
org = "ballerinax"
name = "health.fhir.r4.terminology"
version = "4.1.2"
distribution = "2201.8.6"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "Terminology"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"
export = ["health.fhir.r4.terminology"]

