[package]
org = "ballerinax"
name = "health.fhir.r4.aubase421"
version = "1.0.0"
distribution = "2201.8.6"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "aubase421"]
export = ["aubase421"]

