name: daily-build-davincihrex100

on:
  schedule:
    - cron: '35 20 * * *'    # 02:05 in LK time (GMT+5:30)
  workflow_dispatch:

jobs:
  build:
     uses: ./.github/workflows/daily-build-executor.yml
     secrets: inherit
     with:
      working_dir: davincihrex100
      