name: daily-build-dkcore320

on:
  schedule:
    - cron: '45 21 * * *'    # 03:15 in LK time (GMT+5:30)
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/daily-build-executor.yml
    secrets: inherit
    with:
      working_dir: dk/dkcore320
